## NLP Text Representation Techniques : Bag of Words (BoW)
The Bag of Words (BoW) model is a fundamental technique in Natural Language Processing (NLP) for representing text data. It simplifies text by treating it as a collection of words, disregarding grammar and word order. The main idea is to create a "bag" of words from the text, where each word's frequency is counted.

Text Representation method used by 65% of basic NLP systems. It transforms unstructured text into structured numerical format.

This technique forms foundation of text classification, sentiment analysis, and other NLP tasks. It is simple yet effective for many applications, making it a popular choice for text representation.

## What is Bag of Words (BoW) ? 
1. **Definition**:  
BoW is a text representation technique that converts text into a numerical format by counting the frequency of each word in a document, while ignoring grammar and word order.

2. **Unordered Collection**: 
In BoW, the text is treated as an unordered collection of words, meaning that the sequence of words does not matter.

3. **Word Frequency Focus**: \
 The primary focus of BoW is on the frequency of words in a document, which helps in understanding the importance of each word in the context of the document.
4. **Historical Foundation**: 
Created in the 1950s, BoW has been a foundational technique in NLP, widely used for various applications such as text classification and sentiment analysis.


### How Bag of Words (BoW) Works ?
1. **Creating a Vocabulary**: \
Collect all unique words from the text corpus to form a vocabulary. Each word in the vocabulary will be represented as a feature in the BoW model.
2. **Count Frequency**: \
For each document, count the frequency of each word from the vocabulary. This results in a vector representation of the document, where each element corresponds to the frequency of a specific word.
3. **Generating BoW Vectors**: \
The frequency counts are used to create a BoW vector for each document. The length of the vector is equal to the size of the vocabulary, and each element represents the count of a specific word in the document.
4. **Ignoring Grammar and Word Order**: \
BoW does not consider the grammar or the order of words in the document. It only focuses on the presence and frequency of words, which simplifies the representation but may lead to loss of contextual information.
5. **Example**: \
Consider the following two sentences:
- Sentence 1: "I love NLP"
- Sentence 2: "NLP is great"    
The vocabulary would be: ["I", "love", "NLP", "is", "great"]. The BoW vectors for the sentences would be:
- Sentence 1: [1, 1, 1, 0, 0]
- Sentence 2: [0, 0, 1, 1, 1] \
In this example, the BoW vectors indicate the frequency of each word in the respective sentences, while ignoring the order of the words.

## Simple BoW Example
| **Document** | **Text Content** | **Vector Representation** |
|--------------|------------------|---------------------------|
| Doc 1   | "John likes to watch movies. Mary likes movies too."     | [1,2,1,1,2,1,1,0,0,0]               |
| Doc 2   | "Mary also likes to watch football games."     | [0,1,1,1,0,1,0,1,1,1]               |

Vocabulary: ["John", "likes", "to", "watch", "movies", "Mary", "too", "also", "football", "games"]

So, if I try to find the vector representation of Doc 2 w.r.t. 
the document 1 then the vector representation of Doc 2 will be [0,1,1,1,0,1,0,1,1,1] because the word "John" is not present in Doc 2 but it is present in Doc 1 so the count of "John" in Doc 2 will be 0 and the count of "likes" in Doc 2 will be 1 because it is present in both documents and so on.

## Applications of Bag of Words (BoW)
1. **Spam Detection**: \
BoW can be used to identify spam emails by analyzing the frequency of certain words that are commonly found in spam messages.
2. **Sentiment Analysis**: \
BoW helps in determining the sentiment of a piece of text by counting the frequency of positive and negative words.
3. **Document Clustering**: \
BoW can be used to group similar documents together based on the frequency of words, which is useful in tasks like topic modeling and information retrieval.
4. **Text Classification**: \
BoW is widely used in text classification tasks, such as categorizing news articles, classifying customer reviews, and organizing large text corpora into predefined categories.
5. **Information Retrieval**: \
BoW can be used in search engines to retrieve relevant documents based on the frequency of query terms in the indexed documents. This helps in improving the accuracy of search results by matching the frequency of words in the query with the frequency of words in the documents.


## Limitations of Bag of Words (BoW)
1. **Loss Semantics**: \
BoW does not capture the meaning of words or the context in which they are used, leading to a loss of semantic information.
2. **Misses Phrases** : \
BoW treats each word independently and does not capture phrases or multi-word expressions, which can be important for understanding the meaning of the text.
3. **Sparse Vectors**: \
BoW can result in high-dimensional and sparse vectors, especially when dealing with large vocabularies, which can lead to computational inefficiency and challenges in model training.
4. **No Word Order**: \
BoW ignores the order of words, which can lead to ambiguity and loss of important contextual information, especially in cases where word order is crucial for understanding the meaning of the text.
5. **Inability to Capture Synonyms**: \
BoW does not account for synonyms, meaning that different words with similar meanings will be treated as distinct features, which can lead to a loss of information and reduced performance in tasks like sentiment analysis and text classification.


In [6]:
# !python -m spacy download en_core_web_md

In [7]:
import spacy 
from numpy import dot 
from numpy.linalg import norm


nlp = spacy.load('en_core_web_md')

doc1 = nlp("I love natural language processing.")
doc2 = nlp("Hi")

similarity = dot(doc1.vector, doc2.vector) / (norm(doc1.vector) * norm(doc2.vector))
print(f"Similarity between Doc 1 and Doc 2: {similarity:.4f}")

Similarity between Doc 1 and Doc 2: 0.1844


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

sentences = ["I love NLP.","NLP is fun!","I enjoy learning NLP."]

vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(sentences)
print("Vocabulary:",vectorizer.get_feature_names_out())
print("Bag of Words")
print(bow.toarray())

Vocabulary: ['enjoy' 'fun' 'is' 'learning' 'love' 'nlp']
Bag of Words
[[0 0 0 0 1 1]
 [0 1 1 0 0 1]
 [1 0 0 1 0 1]]


Vocabulary: ['enjoy' 'fun' 'is' 'learning' 'love' 'nlp']
Bag of Words
[[0 0 0 0 1 1]
 [0 1 1 0 0 1]
 [1 0 0 1 0 1]]  This output shows the BoW representation of the three sentences, where each row corresponds to a sentence and each column corresponds to a word in the vocabulary. The values in the matrix indicate the frequency of each word in the respective sentences.

 It comes from the fact that the word "enjoy" appears once in the third sentence, "fun" appears once in the second sentence, "is" appears once in the second sentence, "learning" appears once in the third sentence, "love" appears once in the first sentence, and "nlp" appears once in all three sentences.

 ### 
  The main sentence is "I love NLP." which contains the words "love" and "nlp", while the second sentence "NLP is fun!" contains the words "is", "fun", and "nlp", and the third sentence "I enjoy learning NLP." contains the words "enjoy", "learning", and "nlp".


In [11]:
import numpy as np
import pandas as pd

df_bow = pd.DataFrame(bow.toarray(), columns=vectorizer.get_feature_names_out())
print(df_bow)

   enjoy  fun  is  learning  love  nlp
0      0    0   0         0     1    1
1      0    1   1         0     0    1
2      1    0   0         1     0    1
