## Support Vector Machines (SVM) : A powerful Machine Learning Algorithm
Support Vector Machines (SVM) is a supervised machine learning algorithm that can be used for both classification and regression tasks. It is particularly effective in high-dimensional spaces and is known for its ability to find the optimal hyperplane that separates different classes in the feature space.


### Core Concept : The Hyperplane
The core idea behind SVM is to find a hyperplane that best separates the data points of different classes. The hyperplane is a decision boundary that maximizes the margin between the classes. The data points that are closest to the hyperplane are called support vectors, and they play a crucial role in defining the position and orientation of the hyperplane.

1. **The Street Analogy**: \
Imagine you are standing on a street, and there are two groups of people on either side. Your goal is to find a line (hyperplane) that best separates the two groups while maximizing the distance (margin) between them. The people closest to the line are the support vectors, and they determine where the line should be placed.
2. **Optimal Hyperplane**: \
 The optimal hyperplane is the one that maximizes the margin between the two classes. This means that it is the line that is as far away as possible from the nearest data points of both classes, ensuring better generalization to unseen data.
3. **The Goal**: \
The goal of SVM is to find the hyperplane that best separates the classes while maximizing the margin. This is achieved by solving an optimization problem that minimizes the classification error while maximizing the margin.

### How SVM Works: Margin and Support Vectors
1. **Margin**: \
The margin is the distance between the hyperplane and the nearest data points from each class. SVM aims to maximize this margin, as a larger margin is associated with better generalization to unseen data. The larger the margin, the lower the generalization error of the classifier.
2. **Support Vectors**: \
Support vectors are the data points that are closest to the hyperplane. They are critical in defining the position and orientation of the hyperplane. The SVM algorithm focuses on these support vectors to determine the optimal hyperplane, as they are the most informative points in the dataset for classification.
3. **Optimization Problem**: \
SVM formulates the problem of finding the optimal hyperplane as a convex optimization problem. The algorithm seeks to minimize the classification error while maximizing the margin, which can be solved using techniques such as quadratic programming.

### Formulation of SVM
The SVM optimization problem can be formulated as follows:
Minimize: \
\[\frac{1}{2} ||w||^2 \]
Subject to: \
\[y_i (w \cdot x_i + b) \geq 1\]
Where:
- \(w\) is the weight vector that defines the hyperplane.
- \(b\) is the bias term.
- \(x_i\) are the training data points.
- \(y_i\) are the corresponding class labels (either +1 or -1).

### Kernel Trick
In cases where the data is not linearly separable, SVM can be extended using the kernel trick. The kernel trick allows SVM to operate in a higher-dimensional space without explicitly computing the coordinates of the data in that space. Common kernels include the linear kernel, polynomial kernel, and radial basis function (RBF) kernel.


### Types of SVM
1. **Linear SVM**: \
Linear SVM is used when the data is linearly separable. It finds a straight hyperplane that separates the classes.
2. **Non-linear SVM**: \
Non-linear SVM is used when the data is not linearly separable. It uses kernel functions to map the data into a higher-dimensional space where a linear hyperplane can be used to separate the classes.

### Advantages of Support Vector Machines(SVM)
1. **Effective in High-Dimensional Spaces**: \
SVM is particularly effective in high-dimensional spaces, making it suitable for text classification and other applications where the number of features is large.
2. **Robust to Overfitting**: \
SVM is less prone to overfitting, especially in cases where the number of features exceeds the number of samples. The margin maximization helps to ensure that the model generalizes well to unseen data.
3. **Versatility**: \
SVM can be used for both classification and regression tasks, making it a versatile algorithm for various applications.
4. **Effective with Non-linear Data**: \
With the use of kernel functions, SVM can effectively handle non-linear data, allowing it to find complex decision boundaries.
5. **Sparsity**: \
SVM models are sparse, meaning that they only use a subset of the training data (the support vectors) to make predictions. This can lead to faster prediction times and reduced memory usage.
6. **Memory Efficiency**: \
SVM can be memory efficient, especially when using the kernel trick, as it does not require explicit computation of the feature space, which can be very large in high-dimensional data.

### Applications of Support Vector Machines(SVM)
1. **Text Classification**: \
SVM is widely used in text classification tasks, such as spam detection, sentiment analysis, and document categorization, due to its effectiveness in high-dimensional spaces.
2. **Image Classification**: \
SVM can be used for image classification tasks, where it can effectively separate different classes of images based on their features.
3. **Bioinformatics**: \
SVM is used in bioinformatics for tasks such as gene expression analysis and protein classification, where it can handle the high-dimensional data typically found in these applications.
4. **Handwriting Recognition**: \
SVM can be applied to handwriting recognition tasks, where it can classify handwritten characters based on their features.
5. **Face Detection**: \
SVM can be used for face detection in images, where it can classify regions of an image as containing a face or not based on the features extracted from the image.
6. **Anomaly Detection**: \
SVM can be used for anomaly detection in various applications, such as fraud detection and network security, where it can identify unusual patterns in the data that may indicate fraudulent activity or security breaches.
7. **Medical Diagnosis**: \
SVM can be applied in medical diagnosis tasks, where it can classify medical images or patient data to assist in diagnosing diseases or conditions.

In [3]:
### 1. Import necessary libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

In [5]:
### 2. Load the dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

### let's use only two features for easy visualization
X = X[:, :2] # use sepal length and sepal width

print("--- Data Loaded and prepared for Binary Classification ---")
print("Features shape:", X.shape)
print("Labels shape:", y.shape)
print("\n")

### 3. Split the dataset into training(80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)
## Random state is set to ensure reproducibility of results, and stratify is used to maintain the same class distribution in both training and testing sets.
## stratify=y ensures that the proportion of each class in the training and testing sets is the same as in the original dataset, 
# which is important for maintaining the representativeness of the data.

### 4. Feature Scaling
### SVM performance is highly sensitive to the scale of the features. Therefore, we will standardize the features to have a mean of 0 and a standard deviation of 1.
## We use StandardScaler from sklearn to perform feature scaling. This will help the SVM algorithm converge faster and improve its performance.
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("---Feature Scaling Completed---")
print("Data has been scaled to have a mean of 0 and standard deviation of 1.")
print("\n")

### 5. Create and train the SVM model
### We will use the SVC (Support Vector Classifier) class from sklearn to create our
### SVM model. We will use a linear kernel for simplicity,
#  but SVM can also work with non-linear kernels like RBF or polynomial for more complex datasets.

### Random state ensures reproducibility of results, and kernel='linear' specifies that we want to use a linear kernel.
model = SVC(kernel='linear')

### Train the model on the training data
model.fit(X_train_scaled, y_train)

print("---SVM Model Trained---")
print("\n")

### 6. Make predictions and evaluate the model
### After training the model, we will use it to make predictions on the test set and evaluate

y_pred = model.predict(X_test_scaled)

### 7. Evaluate the Model's Performance

print("---Model Evaluation---")
print("\n")

## confusion matrix
print("Confusion Matrix:")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\n")

### Interpretation 
## [[10 0]] -> 10 samples of class 0 were correctly classified as class 0, and there were no misclassifications for class 0.
## [0 10]] -> 10 samples of class 1 were correctly classified as class

## Accuracy Score 
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\n")

## Classification Report (includes precision, recall, f1-score)
print("Classification Report:")
report = classification_report(y_test, y_pred)
print(report)
print("\n")







--- Data Loaded and prepared for Binary Classification ---
Features shape: (150, 2)
Labels shape: (150,)


---Feature Scaling Completed---
Data has been scaled to have a mean of 0 and standard deviation of 1.


---SVM Model Trained---


---Model Evaluation---


Confusion Matrix:
[[10  0  0]
 [ 0  5  5]
 [ 0  3  7]]


Accuracy: 0.7333333333333333


Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.62      0.50      0.56        10
           2       0.58      0.70      0.64        10

    accuracy                           0.73        30
   macro avg       0.74      0.73      0.73        30
weighted avg       0.74      0.73      0.73        30



